### ISSUE TITLE
10.16.0 version does not seem to include squashed files

### ISSUE THREAD

**Issue by kgunnar** [slee047/node-packer#11]
Creating a very simple "test.js" file that simply runs a console.log command and building it with nodec test.js completes successfully and creates an "a.out" file but a.out returns an error upon execution:
```
./a.out 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/__enclose_io_memfs__/test.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:833:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
Looking in the tmpdir, it seems to have created the squashfs OK so it seems like the Node.js side might not be looking for it properly / in the correct location?

**Comment by sido420** [comment]
same issue here

**Comment by slee047** [comment]
Can you please share the exact test.js source code, and the OS you are using? I believe this does not happen in Windows but I just don't have any idea right now.

**Comment by slee047** [comment]
For some reason, I just fail my test case exclusively in Linux due to the error above:

[https://travis-ci.org/slee047/node-packer/builds/570427117](https://travis-ci.org/slee047/node-packer/builds/570427117)

However, Travis CI can build on XCode 10.2 image (Not 11 for another reason), and AppVeyor builds on Windows.

Therefore, I recommend Linux users to use 10.15.3 release instead.

**Comment by slee047** [comment]
Ok, here is what I found:

1) Windows, macOS can be compiled in full from the Appveyor and Travis using Visual Studio 2017 and XCode Clang respectively. Therefore, I was unable to produce the issue in these platforms.

2) Travis CI has been failing to build for Ubuntu Bionic. I have a VM myself to test this outside of VM by exporting the same variables and install the same version of tools used by Travis as well. The test still fails. I have tried things like using stock Ruby (2.5.3), Ruby 2.6.3 via RVM, stock GCC / G++, Clang 8 / Clang++ 8. All failed.

3) At the same time, I have tested this on CentOS 7.6, with success on RVM 2.6.3, GCC-7 and G++-7. Even replacing GCC-7, G++-7 with Clang-5, Clang++-5 also can compile the test scripts without issue.

Therefore, it is suggesting a Ubuntu (Bionic?) related bug more than bugs within nodec. I am confirming this with Xenial in Travis.

**Comment by sido420** [comment]
So,I ran it on a centos container but as soon as I ran the nodec process it fails with the following error:
```
[root@1b8e2b3eea24 ~]# ll node-packer-1.6.0-10.16.2/bin/
total 8
-rwxrwxr-x 1 root root 3976 Aug 13 07:51 nodec
-rwxrwxr-x 1 root root   30 Aug 13 07:51 nodec.bat
[root@1b8e2b3eea24 ~]# cd /root/node-packer-1.6.0-10.16.2/
[root@1b8e2b3eea24 node-packer-1.6.0-10.16.2]# bin/nodec --make-args="-j3"  --output=/root/a.out --clean-tmpdir --skip-npm-install  /root/test.js
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': /root/node-packer-1.6.0-10.16.2/lib/compiler.rb:149: syntax error, unexpected '.' (SyntaxError)                                                 
    @package_json = @npm_package&.package_json
                                  ^
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from bin/nodec:12:in `<main>'

```

**Comment by sido420** [comment]
That was a ruby issue so plz disregard.

**Comment by sido420** [comment]
Got this error this time in Centos:
```
make[1]: *** [/tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/node_lib/src/cares_wrap.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm 2e2af58e687b01401091d3019a96eb432896c691.intermediate b35ce28b9a4f64e0c2c4a8683ced1e08568dd812.intermediate a35faa891071ed6ef02cbaea29ab215c8c9d1365.intermediate                                                     
make[1]: Leaving directory `/tmp/nodec/node-10.16.2-1.6.0/out'
make: *** [node] Error 2
Failed running ["make -j3"]
```

command used:
```
bin/nodec --make-args="-j3"  --output=/root/a.out --clean-tmpdir --skip-npm-install  /root/proj/index.js  
```

**Comment by slee047** [comment]
> Got this error this time in Centos:
> 
> ```
> make[1]: *** [/tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/node_lib/src/cares_wrap.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> rm 2e2af58e687b01401091d3019a96eb432896c691.intermediate b35ce28b9a4f64e0c2c4a8683ced1e08568dd812.intermediate a35faa891071ed6ef02cbaea29ab215c8c9d1365.intermediate                                                     
> make[1]: Leaving directory `/tmp/nodec/node-10.16.2-1.6.0/out'
> make: *** [node] Error 2
> Failed running ["make -j3"]
> ```
> 
> command used:
> 
> ```
> bin/nodec --make-args="-j3"  --output=/root/a.out --clean-tmpdir --skip-npm-install  /root/proj/index.js  
> ```

Can you please check what is the version of make (cmake), as well as C / C++ compiler used?

And which CentOS version is this? The default GCC shipped with CentOS is lower than supported version, hence you will need to upgrade it manually to GCC 5 or 7 (Recommended). I have never tested it on GCC 6 and 8 with success yet.

**Comment by sido420** [comment]
```
CentOS Linux release 7.6.1810 (Core) 

GNU Make 3.82
Built for x86_64-redhat-linux-gnu

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
```
I will upgrade gcc version and report back asap.

**Comment by sido420** [comment]
same issue:

```
....
/tools/icu/libicudata.a /tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/tools/icu/libicustubdata.a /tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/deps/v8/gypfiles/libv8_snapshot.a -ldl -lrt -lm -Wl,--end-group
rm 2e2af58e687b01401091d3019a96eb432896c691.intermediate b35ce28b9a4f64e0c2c4a8683ced1e08568dd812.intermediate a35faa891071ed6ef02cbaea29ab215c8c9d1365.intermediate                                                     
make[1]: Leaving directory `/tmp/nodec/node-10.16.2-1.6.0/out'
if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
-> cd /root/node-packer-1.6.0-10.16.2
-> cp "/tmp/nodec/node-10.16.2-1.6.0/out/Release/node" "/root/a.out"
[root@baa8582eb270 node-packer-1.6.0-10.16.2]# /root/a.out
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/__enclose_io_memfs__/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:835:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

[root@baa8582eb270 node-packer-1.6.0-10.16.2]# gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
..
[root@baa8582eb270 node-packer-1.6.0-10.16.2]# make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
```
Is `make` version an issue this time?

**Comment by sido420** [comment]
command used:
```
bin/nodec --make-args="-j3"  --output=/root/a.out --clean-tmpdir --skip-npm-install  /root/proj/index.js
```

**Comment by slee047** [comment]
> same issue:
> 
> ```
> ....
> /tools/icu/libicudata.a /tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/tools/icu/libicustubdata.a /tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/deps/v8/gypfiles/libv8_snapshot.a -ldl -lrt -lm -Wl,--end-group
> rm 2e2af58e687b01401091d3019a96eb432896c691.intermediate b35ce28b9a4f64e0c2c4a8683ced1e08568dd812.intermediate a35faa891071ed6ef02cbaea29ab215c8c9d1365.intermediate                                                     
> make[1]: Leaving directory `/tmp/nodec/node-10.16.2-1.6.0/out'
> if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
> -> cd /root/node-packer-1.6.0-10.16.2
> -> cp "/tmp/nodec/node-10.16.2-1.6.0/out/Release/node" "/root/a.out"
> [root@baa8582eb270 node-packer-1.6.0-10.16.2]# /root/a.out
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module '/__enclose_io_memfs__/index.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:835:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> 
> [root@baa8582eb270 node-packer-1.6.0-10.16.2]# gcc --version
> gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
> ..
> [root@baa8582eb270 node-packer-1.6.0-10.16.2]# make --version
> GNU Make 3.82
> Built for x86_64-redhat-linux-gnu
> ```
> 
> Is `make` version an issue this time?

According to the original repo (This is a forked repo), the requirement is that 
Either
1A) GCC and G++ 4.9.4 or newer
OR
1B) CLang and CLang++ 3.4.2 or newer

AND
2) GNU Make 3.8.1 or newer

Right now, your GCC is the same as mine, but mine GNU make is 4.2.1

I am not sure if the code changes have any impact on minimum system requirements.

![github](https://user-images.githubusercontent.com/25880359/63160353-21e3ba80-c050-11e9-8e2d-32feff3979b9.PNG)


I am using the same command as you too, with the exception of some path difference. I will try to upload my minimal project source code + command screenshots + print out logs as a zip file on next monday if possible.

**Comment by sido420** [comment]
I tried with make 4.2.1 as well but same error as soon as I run the code:

```
/tools/icu/libicudata.a /tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/tools/icu/libicustubdata.a /tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/deps/v8/gypfiles/libv8_snapshot.a -ldl -lrt -lm -Wl,--end-group
rm 2e2af58e687b01401091d3019a96eb432896c691.intermediate b35ce28b9a4f64e0c2c4a8683ced1e08568dd812.intermediate a35faa891071ed6ef02cbaea29ab215c8c9d1365.intermediate                                                     
if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
-> cd /root/node-packer-1.6.0-10.16.2
-> cp "/tmp/nodec/node-10.16.2-1.6.0/out/Release/node" "/root/a.out"

[root@017366ec3748 node-packer-1.6.0-10.16.2]# /root/a.out
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/__enclose_io_memfs__/test.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:835:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

[root@017366ec3748 node-packer-1.6.0-10.16.2]# which g++ gcc clang make
/opt/rh/devtoolset-7/root/usr/bin/g++
/opt/rh/devtoolset-7/root/usr/bin/gcc
/opt/rh/llvm-toolset-7/root/usr/bin/clang
/opt/rh/devtoolset-7/root/usr/bin/make

[root@017366ec3748 node-packer-1.6.0-10.16.2]# make --version
GNU Make 4.2.1
..
root@017366ec3748 node-packer-1.6.0-10.16.2]# node -v
v10.16.2
```

If you are using the same version of CentOS, can you provide instructions on how you setup the OS and libraries? 

If not already, you can use a docker Centos container to build and run.

**Comment by sido420** [comment]
1.6.0 with node 10.15.3 seems to work on Centos. So, its the issue with the new version (either packer or node) and probably nothing to do with Linux distro.

**Comment by slee047** [comment]
> 1.6.0 with node 10.15.3 seems to work on Centos. So, its the issue with the new version (either packer or node) and probably nothing to do with Linux distro.

I suspect this has to do with the ability to get the Travis script build successfully or not. The previous time where Travis successfully build on all test cases (macOS and Linux) was 10.15.3.

**Comment by slee047** [comment]
> I tried with make 4.2.1 as well but same error as soon as I run the code:
> 
> ```
> /tools/icu/libicudata.a /tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/tools/icu/libicustubdata.a /tmp/nodec/node-10.16.2-1.6.0/out/Release/obj.target/deps/v8/gypfiles/libv8_snapshot.a -ldl -lrt -lm -Wl,--end-group
> rm 2e2af58e687b01401091d3019a96eb432896c691.intermediate b35ce28b9a4f64e0c2c4a8683ced1e08568dd812.intermediate a35faa891071ed6ef02cbaea29ab215c8c9d1365.intermediate                                                     
> if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
> -> cd /root/node-packer-1.6.0-10.16.2
> -> cp "/tmp/nodec/node-10.16.2-1.6.0/out/Release/node" "/root/a.out"
> 
> [root@017366ec3748 node-packer-1.6.0-10.16.2]# /root/a.out
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module '/__enclose_io_memfs__/test.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:835:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> 
> [root@017366ec3748 node-packer-1.6.0-10.16.2]# which g++ gcc clang make
> /opt/rh/devtoolset-7/root/usr/bin/g++
> /opt/rh/devtoolset-7/root/usr/bin/gcc
> /opt/rh/llvm-toolset-7/root/usr/bin/clang
> /opt/rh/devtoolset-7/root/usr/bin/make
> 
> [root@017366ec3748 node-packer-1.6.0-10.16.2]# make --version
> GNU Make 4.2.1
> ..
> root@017366ec3748 node-packer-1.6.0-10.16.2]# node -v
> v10.16.2
> ```
> 
> If you are using the same version of CentOS, can you provide instructions on how you setup the OS and libraries?
> 
> If not already, you can use a docker Centos container to build and run.

Sorry for the delay, anyway, Node.js has released 10.16.3 which is a security fix. Therefore, we shall be using 10.16.3 to see if this issue is fixed or not.


So, this is how I setup my CentOS in VirtualBox:

1) Install CentOS using DVD ISO and update it during initial boot.

2) Install Node.js 10 with this method:
`sudo yum install curl wget

curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -

sudo yum install nodejs
`

3) Install GCC-7 / G++-7 and CMake 3, set them as default (CentOS 7 default ships with GCC-4.8.5 which is lower than minimum required - 4.9.4. GCC-7 is selected as it is the default for Ubuntu Bionic)
`
sudo yum install centos-release-scl

wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

sudo rpm -ivh epel-release-latest-7.noarch.rpm

sudo yum install yum-utils

sudo yum-config-manager --add-repo https://copr.fedorainfracloud.org/coprs/g/kdesig/cmake3_EPEL/repo/epel-7/heliocastro-cmake3_EPEL-epel-7.repo

sudo yum install openssl openssl-devel libcurl-devel wget tar m4 git-core boost-static m4 gcc-c++ ncurses-devel which make ncurses-static zlib-devel zlib-static devtoolset-7 llvm-toolset-7 llvm-toolset-7-clang-analyzer llvm-toolset-7-clang-tools-extra protobuf-devel protobuf-static jemalloc-devel patch cmake3 bzip2

scl enable devtoolset-7 llvm-toolset-7 bash

echo "source scl_source enable devtoolset-7 llvm-toolset-7" >> ~/.bashrc

sudo alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake3 20 --slave /usr/local/bin/ctest ctest /usr/bin/ctest3 --slave /usr/local/bin/cpack cpack /usr/bin/cpack3 --slave /usr/local/bin/ccmake ccmake /usr/bin/ccmake3 --family cmake

sudo ln -s /usr/bin/cmake3 /usr/bin/cmake
`

4) Install Ruby 2.6.3 via RVM (There are other ways, but this method is selected to mimic Travis CI's way of installing Ruby)

5) Install nasm by compiling from source (The latest version is 2.14.02, CentOS repo provided an old version of 2.10.07 while Ubuntu repo provided an outdated 2.13.02 version)
[http://www.linuxfromscratch.org/blfs/view/svn/general/nasm.html](url)

6) Install squashfstools by
`sudo yum install squashfs-tools`

7) Do a git pull from the current repo, for 10.16.3, I am pushing it under 'TestSeries10' branch for now because it may take 20 ~ 40 commits just to test a new build (Most of them were Travis yml changes only, but sometimes I did tried modifying on certain .js files under node/lib or node/test)

8) Copy these files (Except .git folder, and .gitignore, .gitmodules) to another folder, free from git tracking. I will pull a coffeescript folder on this folder itself due to the way how the test script was designed. For reference, this folder will be at **/home/user/Desktop/Series10**.

Pull the coffeescript by:
`git clone --depth 1 https://github.com/jashkenas/coffeescript.git`

9) Execute the following command in cmd:
`
export arch=x64
export mode=release
export NODEC_TESTS_TMPDIR=/home/user/Desktop/tmp
export PRJROOT_DIR=**"/home/user/Desktop/Series10"**
mkdir -p $NODEC_TESTS_TMPDIR
export TEST_SCRIPT=coffeescript_1
cd Series10
ruby tests/$TEST_SCRIPT || exit $?
`

Note 1: PRJROOT_DIR refers to the actual directory in Step 8.
Note 2: NODEC_TESTS_TMPDIR refers to a temp folder, where the compilation cache will be stored at.
Note 3: There are 3 valid TEST_SCRIPT values: coffeescript_1, coffeescript_2 and datetime.

For coffescript_1, here's my result:
![1](https://user-images.githubusercontent.com/25880359/63211653-d94dff00-c12c-11e9-9578-8a9f62eb3cd4.png)



For Ubuntu Bionic, the setup procedures is almost the same as CentOS by using Ubuntu 18.04.3 ISO except:

2) Install Node.js 10
`
sudo apt install curl wget

curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -`

sudo apt install nodejs
`

3) Install compilation tools in Ubuntu (Number of packages required compared to CentOS is much less because Ubuntu ships gcc-7 and g++-7 by default)
sudo apt-get install build-essential protobuf-compiler python libprotobuf-dev libcurl4-openssl-dev libboost-all-dev libncurses5-dev libjemalloc-dev wget m4 curl clang cmake libssl-dev mg bzip2

6) Install squashfstools by
`sudo apt install squashfs-tools`


I do not have the result yet for Bionic, I will reply as soon as a test result is available.

**Comment by slee047** [comment]
> command used:
> 
> ```
> bin/nodec --make-args="-j3"  --output=/root/a.out --clean-tmpdir --skip-npm-install  /root/proj/index.js
> ```

On top of showing how CentOS passed all the Travis scripts by running it manually, while Ubuntu fails in coffeescript_1 and datetime (Both of scripts involved compiling to an executable file), I would also like to share that in the **StarterKit** branch of this repo, I have prepared a HelloWorld.js script that prints Hello World and its corresponding Node.js version.

I have attempted to run this as 2 test cases:

Test Case A has the following lines in the batch file:
`#!/bin/bash`
`SRC=$(realpath "$(dirname "$BASH_SOURCE")")`
`ruby "${SRC}/Series10/bin/nodec" "${SRC}/Hello_World/HelloWorld.js" -r "${SRC}/Hello_World" -d "${SRC}/tmp" -o "Unix.bin" --clean-tmpdir`

Where the value of SRC refers the location of batch script file resides. It is assumed that the project source code is located under 'Hello_World' folder. It is also assumed that the nodec is copied under a folder called 'Series10'.

Test Case B has the following lines in the batch file:
`#!/bin/bash`
`SRC=$(realpath "$(dirname "$BASH_SOURCE")")`
`Series10/bin/nodec --make-args="-j3"  --output=Unix.out --clean-tmpdir --skip-npm-install  "${SRC}/Hello_World/HelloWorld.js" `

Using the same directory structure as Test Case A, I have tried to run this exactly as the command you have used previously instead (After adjusting for directory requirements).


Screenshots:

Test Case A in CentOS:
![CentOS_HelloWorld](https://user-images.githubusercontent.com/25880359/63221627-5a110780-c1ce-11e9-8f9f-3c5fd3ff0d99.png)


Test Case B in CentOS:
![CentOS_Code](https://user-images.githubusercontent.com/25880359/63221630-62694280-c1ce-11e9-9edf-0f528f5c1148.png)


They can run in the browser flawlessly.

**Comment by slee047** [comment]
For the entire issue, I have managed to create a log file based on Ubuntu Test Case B above.
[code.log](https://github.com/slee047/node-packer/files/3512873/code.log)

This issue definitely happens in Ubuntu Bionic (and likely other Debian / Ubuntu based distros), but I cannot replicate it in CentOS (and likely other Red Hat based distros)............

**Comment by roytan883** [comment]
if 10.15.3 works on ubuntu, but 10.16.x not. That means there must be some nodejs code changes lead this bug, not the system (because the system not chagne). We should focus on what nodejs code changes lead this.
