### ISSUE TITLE
Plans for 12 series ?

### ISSUE THREAD

**Issue by Asp3ctus** [slee047/node-packer#13]
Any plans to support nodejs 12 series ?

**Comment by slee047** [comment]
Good question, but as long as this issue below is not fixed, I would not want to launch a Series12:
https://github.com/slee047/node-packer/issues/11

**Comment by roytan883** [comment]
@slee047 is TestSeries12 work now? I saw it already update to 12.10.0

**Comment by slee047** [comment]
> @slee047 is TestSeries12 work now? I saw it already update to 12.10.0

No. I intend to try again when new Node.js 12 is out. I do not know what is causing the failure. I think the build history is public.

**Comment by slee047** [comment]
Help required on Series12 (Currently on repo TestSeries12).

I have the AppVeyor build here:
[https://ci.appveyor.com/project/slee047/node-packer/builds/27983668](https://ci.appveyor.com/project/slee047/node-packer/builds/27983668)

It fails within a minute or 2 due to this message:

> Looking for Python
> The system cannot find the batch label specified - found-python2
> The system cannot find the batch label specified - done-path-v2
> Failed running ["call vcbuild.bat  x64"]


As for Linux and macOS, I used TravisCI which failed also:
[https://travis-ci.org/slee047/node-packer/builds/595531980](https://travis-ci.org/slee047/node-packer/builds/595531980)


The reason for it to fail seemed to do with 'unresolved external symbols', which is the same as this log when I run it on Windows outside AppVeyor.
[test.log](https://github.com/slee047/node-packer/files/3710059/test.log)

**Comment by roytan883** [comment]
@slee047 same issue here. I test your branch 12 on ubuntu 18.04 server, it compile with error:
```
../deps/uv/src/unix/core.c:1007: undefined reference to `enclose_io_open'
../deps/uv/src/unix/core.c:748: undefined reference to `enclose_io_chdir'
../deps/uv/src/unix/signal.c:121: undefined reference to `enclose_io_read'
```
related with enclose_io_* functions. Maybe it related with `pmq20/libsquash` or `pmq20/libautoupdate` which are include with http://enclose.io

node 12 is LTS now, we should somehow fix it.

**Comment by slee047** [comment]
> @slee047 same issue here. I test your branch 12 on ubuntu 18.04 server, it compile with error:
> 
> ```
> ../deps/uv/src/unix/core.c:1007: undefined reference to `enclose_io_open'
> ../deps/uv/src/unix/core.c:748: undefined reference to `enclose_io_chdir'
> ../deps/uv/src/unix/signal.c:121: undefined reference to `enclose_io_read'
> ```
> 
> related with enclose_io_* functions. Maybe it related with `pmq20/libsquash` or `pmq20/libautoupdate` which are include with http://enclose.io
> 
> node 12 is LTS now, we should somehow fix it.

I agreed. It tends to report > 100 (of similar) problems but I just didnt know how to fix it.

**Comment by slee047** [comment]
> those enclose_io_* functions are here:
> 
> ```
>  node-packer/node/deps/libsquash/sample/enclose_io_unix.c 
> ```
> 
> it seems somehow it not compile or not link. is there something missing in Makefile?

I doubt so, under deps/libsquash (And deps/libautoupdate for this matter), I did not change anything from there. So it should be the same from the original repo.

It works for CentOS 7 for 10.16.3 and both CentOS 7 + Ubuntu 18.04 LTS for 10.15.3.

There is already an issue (Unrelated to this extern stuff) on 10.16.X series for Debian based distros including but not limited to Ubuntu.

I suggest to test in CentOS or Red Hat or Fedora first (To ensure working) before testing on Debian or Ubuntu.

**Comment by roytan883** [comment]
@slee047 
Series12 has something new, my error goes here. I found that 
12 has this folder: `node-packer/node/tools/code_cache`
10 don't have. Maybe the new module new configure to use `libsquash`
```
g++ -o /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/mkcodecache -pthread -rdynamic -m64 -Wl,--whole-archive /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/zlib/libzlib.a -Wl,--no-whole-archive -Wl,--whole-archive /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/uv/libuv.a -Wl,--no-whole-archive -Wl,-z,noexecstack -Wl,--whole-archive /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/tools/v8_gypfiles/libv8_snapshot.a -Wl,--no-whole-archive -Wl,-z,relro -Wl,-z,now -Wl,--whole-archive,/home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/openssl/libopenssl.a -Wl,--no-whole-archive -pthread  -Wl,--start-group /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/mkcodecache/src/node_snapshot_stub.o /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/mkcodecache/src/node_code_cache_stub.o /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/mkcodecache/tools/code_cache/mkcodecache.o /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/mkcodecache/tools/code_cache/cache_builder.o /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/libnode.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/histogram/libhistogram.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/tools/v8_gypfiles/libv8_libplatform.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/tools/icu/libicui18n.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/zlib/libzlib.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/http_parser/libhttp_parser.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/llhttp/libllhttp.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/cares/libcares.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/uv/libuv.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/nghttp2/libnghttp2.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/brotli/libbrotli.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/deps/openssl/libopenssl.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/tools/v8_gypfiles/libv8_base_without_compiler.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/tools/icu/libicuucx.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/tools/icu/libicudata.a /home/rtsu/packer/_compile_tmp_12/node-12.13.0-1.6.0/out/Release/obj.target/tools/icu/libicustubdata.a 
```

**Comment by roytan883** [comment]
@slee047 In node.gyp
```
{
	      'target_name': '<(node_lib_target_name)',
	      'type': '<(node_intermediate_lib_type)',
	      'product_name': '<(node_core_target_name)',
	
	      'dependencies': [
	        'deps/nghttp2/nghttp2.gyp:nghttp2',
	        'deps/libsquash/enclose_io_libsquash.gyp:enclose_io_libsquash',
	        'deps/libautoupdate/libautoupdate.gyp:libautoupdate',
	      ],
	      'includes': [
	        'node.gypi',
	      ],
	
	      'include_dirs': [
	        'src',
	        'tools/msvs/genfiles',
	        'deps/uv/src/ares',
	        'deps/nghttp2/lib/includes',
	        'deps/libsquash/include',
	        'deps/libsquash/sample',
	        'deps/libautoupdate/include',
	        '<(SHARED_INTERMEDIATE_DIR)', # for node_natives.h
	      ],
	      'dependencies': [ 'deps/histogram/histogram.gyp:histogram' ],
```
In Series12 is second **dependencies** overwrite the first **dependencies** ? Series10 is not overwrite . If this overwrite happen, then `libsquash` is not compiler with '<(node_lib_target_name)', but lots of sub-module depend on it.

**Comment by roytan883** [comment]
@slee047 compile OK now. But when run a.out, show this error:
```
 ./a.out
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/__enclose_io_memfs__/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1031:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by roytan883** [comment]
@slee047 So, this maybe system issue now.
I compiled `TestSeries12` (with gcc/g++ 7.4.0) on `Ubuntu Server 14.04.3 LTS`, it works.

But after i copy a.out to `Ubuntu Server 18.04.3 LTS`, it show the `Cannot find module '/__enclose_io_memfs__/app.js'` error.

**Comment by slee047** [comment]
> @slee047 So, this maybe system issue now.
> I compiled `TestSeries12` (with gcc/g++ 7.4.0) on `Ubuntu Server 14.04.3 LTS`, it works.
> 
> But after i copy a.out to `Ubuntu Server 18.04.3 LTS`, it show the `Cannot find module '/__enclose_io_memfs__/app.js'` error.

Thanks for feedback, let me try it as well.

**Comment by roytan883** [comment]
@slee047 `Ubuntu Server 16.04.6 LTS` also works.

**Comment by slee047** [comment]
> @slee047 `Ubuntu Server 16.04.6 LTS` also works.
Wow, could you please help me check if 10.16.3 works in Ubuntu before (and excluding) 18.04 LTS?
I know 18.04 dont work and Debian 10 don't. Based on the statements, most likely Debian 8 works.

**Comment by roytan883** [comment]
@slee047 10.16.3 was `Segmentation fault (core dumped)` on `Ubuntu Server 14.04.3 LTS`, but `10.15.3` is OK.

**Comment by roytan883** [comment]
@slee047 The reason of `18.04 Ubuntu` can't work was found: 

The right way libuv access all `fs` related C/C++ function should overwrite by `enclosed_io_*`, like this:
```
#define stat(...)	enclose_io_stat(__VA_ARGS__)
```
But somehow when run it on `18.04 Ubuntu`, the overwrite is not work, the a.out still use `STD` functions.

Here are log on `14.04 Ubuntu`:
```
roytanj Module._resolveFilename : express Module {
  id: '.',
  path: '/__enclose_io_memfs__',
  exports: {},
  parent: null,
  filename: '/__enclose_io_memfs__/app.js',
  loaded: false,
  children: [],
  paths: [ '/__enclose_io_memfs__/node_modules', '/node_modules' ]
} false undefined
roytanj qqq paths [
  '/__enclose_io_memfs__/node_modules',
  '/node_modules',
  '/home/rtsu/.node_modules',
  '/home/rtsu/.node_libraries',
  '/home/rtsu/tmp/lib/node'
]
roytanj Module._findPath : express [
  '/__enclose_io_memfs__/node_modules',
  '/node_modules',
  '/home/rtsu/.node_modules',
  '/home/rtsu/.node_libraries',
  '/home/rtsu/tmp/lib/node'
] false
roytanj Module._findPath 111 paths: [
  '/__enclose_io_memfs__/node_modules',
  '/node_modules',
  '/home/rtsu/.node_modules',
  '/home/rtsu/.node_libraries',
  '/home/rtsu/tmp/lib/node'
]
roytanj Module._findPath 222
roytanj Module._findPath 333
roytanj stat filename =  /__enclose_io_memfs__/node_modules
roytanj stat 1 result =  undefined
roytanc InternalModuleStat path = /__enclose_io_memfs__/node_modules
roytanc enclose_io_stat 2 = /__enclose_io_memfs__/node_modules
roytanj stat 2 result =  1
```

But after copy the a.out to `18.04 Ubuntu`, the log are:
```
roytanj Module._resolveFilename : express Module {
  id: '.',
  path: '/__enclose_io_memfs__',
  exports: {},
  parent: null,
  filename: '/__enclose_io_memfs__/app.js',
  loaded: false,
  children: [],
  paths: [ '/__enclose_io_memfs__/node_modules', '/node_modules' ]
} false undefined
roytanj qqq paths [
  '/__enclose_io_memfs__/node_modules',
  '/node_modules',
  '/home/rtsu/.node_modules',
  '/home/rtsu/.node_libraries',
  '/home/rtsu/lib/node'
]
roytanj Module._findPath : express [
  '/__enclose_io_memfs__/node_modules',
  '/node_modules',
  '/home/rtsu/.node_modules',
  '/home/rtsu/.node_libraries',
  '/home/rtsu/lib/node'
] false
roytanj Module._findPath 111 paths: [
  '/__enclose_io_memfs__/node_modules',
  '/node_modules',
  '/home/rtsu/.node_modules',
  '/home/rtsu/.node_libraries',
  '/home/rtsu/lib/node'
]
roytanj Module._findPath 222
roytanj Module._findPath 333
roytanj stat filename =  /__enclose_io_memfs__/node_modules
roytanj stat 1 result =  undefined
roytanc InternalModuleStat path = /__enclose_io_memfs__/node_modules
roytanj stat 2 result =  -2
```

> InternalModuleStat -> uv_fs_stat -> stat -> enclose_io_stat

on `18.04 Ubuntu` it runs:

> InternalModuleStat -> uv_fs_stat -> stat

But i'm confused that why the same a.out can have different behavior on different system. Because the a.out already is a solid binary which static link with libsquash, which means the overwrite
`#define stat(...)	enclose_io_stat(__VA_ARGS__)` should work.

**Comment by slee047** [comment]
> @slee047 The reason of `18.04 Ubuntu` can't work was found:
> 
> The right way libuv access all `fs` related C/C++ function should overwrite by `enclosed_io_*`, like this:
> 
> ```
> #define stat(...)	enclose_io_stat(__VA_ARGS__)
> ```
> 
> But somehow when run it on `18.04 Ubuntu`, the overwrite is not work, the a.out still use `STD` functions.
> 
> Here are log on `14.04 Ubuntu`:
> 
> ```
> roytanj Module._resolveFilename : express Module {
>   id: '.',
>   path: '/__enclose_io_memfs__',
>   exports: {},
>   parent: null,
>   filename: '/__enclose_io_memfs__/app.js',
>   loaded: false,
>   children: [],
>   paths: [ '/__enclose_io_memfs__/node_modules', '/node_modules' ]
> } false undefined
> roytanj qqq paths [
>   '/__enclose_io_memfs__/node_modules',
>   '/node_modules',
>   '/home/rtsu/.node_modules',
>   '/home/rtsu/.node_libraries',
>   '/home/rtsu/tmp/lib/node'
> ]
> roytanj Module._findPath : express [
>   '/__enclose_io_memfs__/node_modules',
>   '/node_modules',
>   '/home/rtsu/.node_modules',
>   '/home/rtsu/.node_libraries',
>   '/home/rtsu/tmp/lib/node'
> ] false
> roytanj Module._findPath 111 paths: [
>   '/__enclose_io_memfs__/node_modules',
>   '/node_modules',
>   '/home/rtsu/.node_modules',
>   '/home/rtsu/.node_libraries',
>   '/home/rtsu/tmp/lib/node'
> ]
> roytanj Module._findPath 222
> roytanj Module._findPath 333
> roytanj stat filename =  /__enclose_io_memfs__/node_modules
> roytanj stat 1 result =  undefined
> roytanc InternalModuleStat path = /__enclose_io_memfs__/node_modules
> roytanc enclose_io_stat 2 = /__enclose_io_memfs__/node_modules
> roytanj stat 2 result =  1
> ```
> 
> But after copy the a.out to `18.04 Ubuntu`, the log are:
> 
> ```
> roytanj Module._resolveFilename : express Module {
>   id: '.',
>   path: '/__enclose_io_memfs__',
>   exports: {},
>   parent: null,
>   filename: '/__enclose_io_memfs__/app.js',
>   loaded: false,
>   children: [],
>   paths: [ '/__enclose_io_memfs__/node_modules', '/node_modules' ]
> } false undefined
> roytanj qqq paths [
>   '/__enclose_io_memfs__/node_modules',
>   '/node_modules',
>   '/home/rtsu/.node_modules',
>   '/home/rtsu/.node_libraries',
>   '/home/rtsu/lib/node'
> ]
> roytanj Module._findPath : express [
>   '/__enclose_io_memfs__/node_modules',
>   '/node_modules',
>   '/home/rtsu/.node_modules',
>   '/home/rtsu/.node_libraries',
>   '/home/rtsu/lib/node'
> ] false
> roytanj Module._findPath 111 paths: [
>   '/__enclose_io_memfs__/node_modules',
>   '/node_modules',
>   '/home/rtsu/.node_modules',
>   '/home/rtsu/.node_libraries',
>   '/home/rtsu/lib/node'
> ]
> roytanj Module._findPath 222
> roytanj Module._findPath 333
> roytanj stat filename =  /__enclose_io_memfs__/node_modules
> roytanj stat 1 result =  undefined
> roytanc InternalModuleStat path = /__enclose_io_memfs__/node_modules
> roytanj stat 2 result =  -2
> ```
> 
> > InternalModuleStat -> uv_fs_stat -> stat -> enclose_io_stat
> 
> on `18.04 Ubuntu` it runs:
> 
> > InternalModuleStat -> uv_fs_stat -> stat
> 
> But i'm confused that why the same a.out can have different behavior on different system. Because the a.out already is a solid binary which static link with libsquash, which means the overwrite
> `#define stat(...) enclose_io_stat(__VA_ARGS__)` should work.

Great investigative skills. Could there be a chance that this is a GCC issue? I remembered that in Series10 or even Series8, if I compile a Node.js application from CentOS, it runs on Ubuntu.

However, CentOS will refuse to run the a.out generated from Ubuntu.


Meanwhile, I have been failing to compile on Windows based on the most recent commit. I did not know where it has gone wrong again (Appveyor have met fatal errors within a minute or two).

So perhaps this wont work on Windows and recent (Debian 9 / Ubuntu 18.04 LTS based) distros?

**Comment by roytan883** [comment]
@slee047 After tons of C/C++ modify and debug(printf). Finally address it from `libuv`, before call real overwrite `stat` function, it test a `syscall` with `statx`, but its `errno` is strange on  `Ubuntu 18.04 LTS`, so it always fail. I simple fix is `modify uv__fs_statx function` in `node/deps/uv/src/unix/fs.c`
```
//roytan-hack-start
//for ubuntu 18.04 or debian
  if (no_statx != 1) {
    no_statx = 1;
  }
//roytan-hack-end
```
because on `Ubuntu 14.04` it alway `no_statx  == 1`. 

Do you know how to detect system version by GCC macro? Then this fix can be only effect on `Ubuntu` or `Debian`.

I'm cleaning code and re-compile it then test. If it wors great, maybe i can send a PR.

**Comment by slee047** [comment]
> @slee047 After tons of C/C++ modify and debug(printf). Finally address it from `libuv`, before call real overwrite `stat` function, it test a `syscall` with `statx`, but its `errno` is strange on `Ubuntu 18.04 LTS`, so it always fail. I simple fix is `modify uv__fs_statx function` in `node/deps/uv/src/unix/fs.c`
> 
> ```
> //roytan-hack-start
> //for ubuntu 18.04 or debian
>   if (no_statx != 1) {
>     no_statx = 1;
>   }
> //roytan-hack-end
> ```
> 
> because on `Ubuntu 14.04` it alway `no_statx == 1`.
> 
> Do you know how to detect system version by GCC macro? Then this fix can be only effect on `Ubuntu` or `Debian`.
> 
> I'm cleaning code and re-compile it then test. If it wors great, maybe i can send a PR.

If no_statx works on CentOS, Red Hat, Fedora or SuSE, then I think just hard code this value instead. I dont expect BSD or other Unix that is neither Linux nor macOS support unless anyone feedback accordingly.

Because there is also Windows support involved, which does not depend on GCC.

**Comment by roytan883** [comment]
@slee047 please do not release Series12, I found that the all `Socket` will auto disconnect in few seconds. I use `Koa` for http, and `pg` for postgresql db connection, both auto disconnect in few seconds. I guess it not related with `/__enclose_io_memfs__`, should be some bug when merge nodejs 12 code.

**Comment by slee047** [comment]
> @slee047 please do not release Series12, I found that the all `Socket` will auto disconnect in few seconds. I use `Koa` for http, and `pg` for postgresql db connection, both auto disconnect in few seconds. I guess it not related with `/__enclose_io_memfs__`, should be some bug when merge nodejs 12 code.

Thanks for the alert. But I have also issues compiling in Windows. I am not sure if this has to do with auto disconnect issue or not.

**Comment by Asp3ctus** [comment]
Any updates on this issue?

**Comment by saurabh-deep** [comment]
Hey @slee047 and @roytan883 ~ I hope this message finds you in good health, with all Coronavirus issues going around the world.

Going by the comments I could read above, it is evident you folks have invested quite a bit of time in it and I can't thank you enough for that. Did you manage to get some success out of your efforts for Series12? Are we any closer to compile with Node 12.x? Can I help you with some testing on Windows, Mac etc?

**Comment by saurabh-deep** [comment]
Hey folks @slee047 and @roytan883 - Just wanted to circle back to this and check if there any chances we can get this to work with Node12.x? Have we abandoned this project? If yes, this is very unfortunate as this is the only fork of the main project which was being maintained at all.

There are other options available such as pkg/nexe, but the binary sizes with them are very large and they all have issues with OSX signing and notarizing.

@Asp3ctus - Were you able to proceed with this? How are you packaging your app now?

**Comment by slee047** [comment]
> Hey folks @slee047 and @roytan883 - Just wanted to circle back to this and check if there any chances we can get this to work with Node12.x? Have we abandoned this project? If yes, this is very unfortunate as this is the only fork of the main project which was being maintained at all.
> 
> There are other options available such as pkg/nexe, but the binary sizes with them are very large and they all have issues with OSX signing and notarizing.
> 
> @Asp3ctus - Were you able to proceed with this? How are you packaging your app now?

Unfortunately no, I have no idea how to make this work in the first place.

**Comment by saurabh-deep** [comment]
@slee047 - Is there anything we can do? It is hard to let node-packer go. The binaries created by this have been very stable and small in size. We don't really want to shift to any other packaging mechanism, unless there is no other way.

What are you using now to package your app?

**Comment by slee047** [comment]
> @slee047 - Is there anything we can do? It is hard to let node-packer go. The binaries created by this have been very stable and small in size. We don't really want to shift to any other packaging mechanism, unless there is no other way.
> 
> What are you using now to package your app?

Yes, it is time to let node-packer go.

I believe that there are some mechanism changes in Node 12 that makes “hacking” way unviable anymore.

Meanwhile, I had also already resigned from my last job on Dec 2019 which needs to use node-packer. Now I am not required to develop in Node.js

**Comment by saurabh-deep** [comment]
Ah! So, this is it for node-packer, unless someone takes this on. Seems very unlikely at this point.

Anyways, thank you for taking it this far after the original project was abandoned. Wish you best of luck for your new job!

**Comment by slee047** [comment]
> Ah! So, this is it for node-packer, unless someone takes this on. Seems very unlikely at this point.
> 
> Anyways, thank you for taking it this far after the original project was abandoned. Wish you best of luck for your new job!

Good news! Apparently the original author will try to update Node.js to 12 LTS. No timeline given by him, and it remains to be seen if the Node 12 LTS changes are insurmountable for the node-packer

https://github.com/pmq20/node-packer/pull/135#issuecomment-626334645

**Comment by saurabh-deep** [comment]
Good news indeed! Thank you @slee047 for posting this update! Will wait eagerly for the outcome, hopefully positive. We are sticking with your Node 10.16.3 version for now.

**Comment by Asp3ctus** [comment]
I guess we need to close this issue.. 
For anyone looking for an alternative, take a lot at https://github.com/vercel/pkg it is well maintained and support latest nodejs versions
